repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: "Lint"
        entry: npm run lint
        language: system
        files: '\.(js|jsx|ts|tsx)$'

      - id: npm-test-e2e
        name: "End-to-End Test"
        entry: npm run test:e2e
        language: system
        # You might want to run this only for certain files or directories
        files: '\.(js|jsx|ts|tsx)$'
        # types: [typescript]
        # exclude: ''

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-mod-tidy

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.3.0
    hooks:
      - id: cspell
