repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: npm-lint
        name: "Lint"
        entry: sh -c 'npm run lint'
        language: system

      - id: npm-test-e2e
        name: "End-to-End Test"
        entry: bash -c 'npm run test:e2e'
        language: system
        require_serial: true #https://pre-commit.com/#hooks-require_serial

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.10.0
    hooks:
      - id: cspell
