services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:ee6da62c34a87250b043db496f128e55b3c82613fd3c95b6caf8deb3604309dd
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:c80a28b4b1c1ec9f8b3673f3a42d9daae5bda38bf88ca6ee1166c833796bbf2c
    container_name: next
    expose:
      - 3000
