services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:bfc7346e35697186cc6c3ef6bafa15603583b4a4e9bd96dcfef9ce39de700f3a
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:64d4429dd8641438bad89c9d1d3774a307d800388758b041d7dcf0028f5a08c3
    container_name: next
    expose:
      - 3000
