services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:652a739d68ed1b61608115f62afda48974eb2f513b1ea0a6cecb4362c9a12409
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:67953df3e57d1dd08d1c9da68ab98571a4ec6d5defe0aa69759fced71348771e
    container_name: next
    expose:
      - 3000
