services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:3a2e45d73b7b816d6632887067553e86a9233615e04f23d125cf431c640f4143
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:08ba3257e1d7fab088e418292cbefc0bf263ea5216c9743acb4b9c835595dfd5
    container_name: next
    expose:
      - 3000
