services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:b5804c9a53442e2e8bb6579426ac3939eca2f832e6561e8f34ebf5ab7dc36747
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:d3e9bc261b3e47b35ac1e0e6fb36ab1cb31bcd0bf5b34ef28f7dc6fc9a50b742
    container_name: next
    expose:
      - 3000
