services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:676272daa592f399634f90b0de2aa0e4614fd8651f0b1eb7b1377479b53422ee
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:dc2a623d086a44f3564b0b85597b51cafa61bfdfda0bbb5a8792375dd9486357
    container_name: next
    expose:
      - 3000
