services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:963ea7194e570f15d85a69d98c4707e5bd7b4400ef91fc1cbcb395c6bfe46c9d
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:0a530e59ae375efcf2ba8787c81b9cbfa5ebebe770a44fc6eeb011337cc00455
    container_name: next
    expose:
      - 3000
