services:
  nginx:
    image: lscr.io/linuxserver/swag:latest@sha256:11ba5fd0a8a2207fc7f7d3b09030cbaaa661299d9ece1367ef61ea371bc321cb
    container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=about.bl4ko.com
      - VALIDATION=http
      # - SUBDOMAINS=www, #optional
      - STAGING=false #optional
    volumes:
      - ./docker/swag:/config
    ports:
      - 443:443
      - 80:80 #Required for certbot validation
    restart: unless-stopped
    depends_on:
      - next

  next:
    image: bl4ko/homepage:latest@sha256:10d965546265f3e47cccdb17688adea55f061ded5143a02d1f6c1139206269ef
    container_name: next
    expose:
      - 3000
