name: Build and deploy application

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker image
    runs-on: [rocky, balboa]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bl4ko/homepage:latest

  deploy:
    name: Deploy application to server
    runs-on: [rocky, balboa]
    needs: build

    steps:
      - name: Add key from variable
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ./key && chmod 600 ./key

      - name: Connect to host and update
        run: |
          ssh -o StrictHostKeyChecking=no -i ./key -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'kubectl rollout restart deployment/portfolio -n portfolio'
