# This actions is used for debugging purposes
# It is maintained on the branch github-actions
name: Debuging action
on:
  workflow_dispatch:

jobs:
  test:
    name: Change me
    runs-on: homepage-runners
    steps:
      - name: Changeme
        run: echo "Change me"
