name: Debuging action
on:
  workflow_dispatch:
    # inputs:
    #   logLevel:
    #     description: "Log level"
    #     required: true
    #     default: "warning"
    #     type: choice
    #     options:
    #       - info
    #       - warning
    #       - debug
    #   tags:
    #     description: "Test scenario tags"
    #     required: false
    #     type: boolean
    #   environment:
    #     description: "Environment to run tests against"
    #     type: choice
    #     default: "test"
    #     required: false
    #     options:
    #       - test
    #       - prod

jobs:
  deploy:
    name: Deploy application to server
    runs-on: k8s-runners
    steps:
      - name: Add key from variable
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > ./key && chmod 600 ./key
      - name: Install ssh client if not installed
        run: |
          sudo apt-get update && sudo apt-get install openssh-client -y
      - name: Connect to host and update
        run: |
          ssh -o StrictHostKeyChecking=no -i ./key -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} 'echo "hello world"'
