name: Links
permissions:
  contents: read
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/links.yml@e3ee3f85ccd9598ea165e61506ee6d9942a5bcae # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
