name: Links
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  permissions:
    contents: read
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/spellcheck.yml@main
    secrets:
      SVC_TOKEN: ${{ secrets.SVC_TOKEN }}
