name: Links
permissions:
  contents: read
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    uses: bl4ko/shared-actions/.github/workflows/links.yml@5e35496524b7c84a8da582145992f4993abaf7fc # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
