name: OSV-Scanner scan Containerfile
on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:
jobs:
  osv_scan_image:
    uses: bl4ko/shared-actions/.github/workflows/osv_image.yml@33aaba12a83e3c7b5f9f854d591645501e57bb19 # main
    permissions:
      contents: read
      packages: write
    with:
      containerfile: ./Dockerfile
