name: OSV-Scanner scan Containerfile
on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:
jobs:
  osv_scan_image:
    uses: bl4ko/shared-actions/.github/workflows/osv_image.yml@9c75ce956f74d070d86002d6d5ab05a53e0316f3 # main
    permissions:
      contents: read
      packages: write
    with:
      containerfile: ./Dockerfile
