name: OSV-Scanner scan Containerfile
on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:
jobs:
  osv_scan_image:
    uses: bl4ko/shared-actions/.github/workflows/osv_image.yml@ad25766a45f6ca9a2f2649e4afbd789adb49fc49 # main
    permissions:
      contents: read
      packages: write
    with:
      containerfile: ./Dockerfile
