name: Create Release 🚀
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@9aa9710eec94de219f6c8c747b13417aaa99449c # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
