name: Create Release 🚀
permissions:
  contents: read
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@96c04bc028d3529c4c2e2a1d023eef989d185d02 # main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
