name: Create Release 🚀
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  permissions:
    contents: read
  release:
    uses: bl4ko/shared-actions/.github/workflows/release.yml@main
    secrets:
      SVC_TOKEN: ${{ secrets.SVC_TOKEN }}
