on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [develop]
jobs:
  trivy:
    name: Trivy Scan
    runs-on: [rocky, balboa]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest trivy version from github
        run: |
          TRIVY_VERSION=$(curl --silent "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Latest Trivy Version: ${TRIVY_VERSION}"
          echo "TRIVY_VERSION=$TRIVY_VERSION" >> $GITHUB_ENV
      - name: Install the latest version of trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin ${{ env.TRIVY_VERSION }}
      - name: Build Docker Image
        run: |
          docker build -t homepage:trivy .
      - name: Trivy Scan Image
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress homepage:trivy
