name: Spellcheck Action
on:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: streetsidesoftware/cspell-action@807d7d92b7057593a2de102168506f298405339d # v6
