name: Spellcheck Action
on:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - uses: streetsidesoftware/cspell-action@807d7d92b7057593a2de102168506f298405339d # v6
