name: Spellcheck Action
on:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: streetsidesoftware/cspell-action@934c74da3775ac844ec89503f666f67efb427fed # v6
